# Site settings
title: Fernando Rubio
twitter_username: fernando_rubi0
name: Fernando Rubio

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
# - title: Blog
#   url: https://automateddeveloper.blogspot.com/
 - title: GitHub
   url: https://github.com/nandorrb
# - title: StackOverflow
#   url: https://stackoverflow.com/users/258813/rhinds
# - title: DZone
#   url: https://dzone.com/users/899489/rhinds.html
 - title: LinkedIn
   url: https://www.linkedin.com/in/fernando-rubio/

#Any buzzword skills you want to include
skills:
 - Embedded systems designes
 - Machines designer
 - PCB design
 - IOT
 - Power machines(Gas and Steam Turbines)
 - Fluid mechanics(Pump design, WaterJet boat proppeler design)
 - Gradle
 - Java
 - Kotlin
 - Android
 - REST
 - Python3

#Blogfeed is optional - including this will add JS to call the feed and populate blog list
#blogfeed: https://automateddeveloper.blogspot.com/feeds/posts/default?alt=json


  
#Education part 2
#education:

#Work experience is required
roles:
 - title: Software Engineer / Android Developer
   start: 2018
   end: 2018
   employer: ForceClose
   description: adadasdadasd.
 - title: Instrumentation and Control Automation Engineer
   start: 2018
   end: 2018
   employer: All Energy Peru SAC
   description: Project of Automation and Control of fuel supply for the generator group of the <a href="http://edificioprimeravision.com/" taget="_blank">Primera Vision building</a>  of the company COSAPI. I designed and implemented the fuel supply system for the First Vision building generator set. I selected the fuel level sensors for the Diesel tanks, designed the control logic (ON / OFF), designed the control board, designed the P&ID diagram, drafted the work procedures for the contracting company, programmed the board PLC control in such a way that it meets the specifications of reporting the values of the sensors via PROFINET to a BMS system.
 - title: Software Engineer / Android developer
   start: 2017
   end: 2017
   employer: Instituto Pacifico SA
   description: Android application development with Android Studio:<br> Programming using good practices in development, correct location of packages, styles, use of gradle, appointment of classes, optimization of memory use.<br> Use of design patterns: Creational, Structural, Behavioral. - Use of web services, tabs, fragments, SQLite, SOAP, REST, etc. <br>  Libraries such as: Retrofit, Glide, ButterKnife, Parceler, IcePick, LeakCanary, Espresso, Robolectric, Zxing, etc. <br> Use of Gradle multiproject Build to compile multiple applications at the same time.
 - title: Associate Manager
   start: 2005
   end: 2012
   employer: Accenture
   description: Working on a range of functional and technical roles, primarily working on client sites in Financial Services in London and Europe.

#Education is required
education:
 - level: Bachelor of Science (B.Sc.)
   date: 2010
   subject: Mechatronic Engineering
   school: Universidad Nacional de Ingenieria - Peru
 - level: Master of Mechanical Engineering
   date: 2018
   subject: Machines and Equipment Design
   school: Technical University of Liberec
   
#This section is optional (as is the image link below)
#coursera:
#   profileurl: https://www.coursera.org/user/i/c6362b4056f755a04bef6a791a62102b
#   courses:
#    - title: Functional Programming Principles in Scala
#      link: https://www.coursera.org/course/progfun
#      optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/progfun/small-icon.hover.png
#      date: September 16, 2013
#    - title: Algorithms Design and Analysis, Part 1
#      link: https://www.coursera.org/specializations/algorithms
#      optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/algo/small-icon.hover.png
#      date: April 28, 2014

#This section is optional - embeds slideshows from speakerdeck
# to get the speakerdeck ID copy the embed code and look for the data-it attribute
#speakerdeck:
#   profileurl: https://speakerdeck.com/robhinds
#   talks:
#    - title: Product Management for Engineers
#      speakerdeckId: 94f0070c4e434ec79fe9b4eb2cb574e0
#      conference: API Conference, Berlin 2018
#    - title: Agile Machine Learning - from Theory to Production
#      speakerdeckId: ec84f2f56e9743afb0675b1eeeb6b6ce
#      conference: W-JAX Conference, Munich 2017 (London 2017)

#List of interesting Github repo/projects to include - optional
github:
 - nandorrb/FluidMechanics
 - nandorrb/WaterJetCalculations 
 - nandorrb/desarrollo_de_aplicaciones
 - nandorrb/FluidMechanics

#Stackoverflow flair is optional
#stackoverflow:
#   profileurl: https://stackoverflow.com/users/258813/rhinds
#   flairimageurl: https://stackoverflow.com/users/flair/258813.png

intro: |
 Mechatronic Engineer Graduated from the National Engineering University (Lima, Peru), with master in Machines and Equipment Design at Technical University of Liberec (Liberec, Czech Republic) with experience in industrial design. I like to work with new technologies such as Android programming, PCB and Machines design. I participated on the Festo mechatronics olympics of Peru: Pneumatics, electropneumatics and PLC programming. Have a good background on mathematics, programming, material Engineering, and design of machines.

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   <strong>Scala</strong>: My current role uses Scala as the primary language and have been building applications in Scala for the last two years. I am familiar with a range of Scala libraries, such as <a target="_blank" href="https://automateddeveloper.blogspot.com/2017/12/an-opinionated-guide-to-building-apis.html"> Akka-Http for building microservices</a> and <a target="_blank" href="https://automateddeveloper.blogspot.com/2018/09/generic-programming-with-scala.html"> Shapeless for generic programming</a>, as well as familiar with a range of <a target="_blank" href="https://basementcrowd.com/2018/11/28/scala-the-aux-pattern-path-dependent-types/" >functional programming techniques available</a>.<br/><br/>
   <strong>Java</strong>: I am experienced in a variety of Java API’s and frameworks. I have worked with Spring 4, Spring Boot, JPA (Hibernate and EclipseLink) in addition to others. <br/><br/>
   <strong>Groovy</strong> I have used Groovy as a language in production for ~4 years and I am familiar with many of the languages features (such as writing <a target='_blank' href="https://dzone.com/articles/functional-programming-groovy">Functional Programming style groovy</a>) and quirks (such as <a target="_blank" href="https://dzone.com/articles/groovy-retrospective-an-addendum-memory-usage-perm">memory leak issues</a>). <br/><br/>
   <strong>Cloud platforms</strong>: I have primarily used AWS for running production apps on the cloud. I have experience setting up, configuring and running applications using a range of AWS offerings, including EC2, RDS, S3, Cogito, <a target="_blank" href="https://automateddeveloper.blogspot.com/2018/05/serverless-with-aws-lambda-scala.html">Lambda</a> and its more recent <a target="_blank" href="https://automateddeveloper.blogspot.com/2018/10/machine-learning-with-aws-scala.html">Machine Learning capabilities</a>.<br/><br/>
   <strong>Web Development</strong>: Through building web applications, I have also worked with various client side technology, having used jQuery, Bootstrap, LESS, SASS, Backbone/Underscore/Require. More recently I have written React applications (primarily using the Create React App framework, and extending them)<br/><br/>
   <strong>Development Control</strong>: I have a good knowledge of application life-cycle management and have worked with SVN, Git, Maven, Gradle, Sonar, Jenkins, TeamCity, etc. I have experience with an array of testing tools and technologies.<br/><br/>
   I have also gained experience and knowledge of other technologies from several side projects and research that I have undertaken in my free time, including Android, a variety of social APIs (Twitter etc) and cloud platforms such as CloudFoundry/OpenShift/AppFog/AWS. <br/><br/>
   As part of Nerdability, I created, and am now primary contributor to, two Spring projects - <a target='_blank' href="https://github.com/robhinds/spring-social-geeklist">Spring-Social-Geeklist</a> and <a target='_blank' href="https://github.com/nerdability/spring-social-khan-academy">Spring-Social-Khan-Academy</a>, which provide core integration with those third-party APIs on top of the Spring Social framework. They are both listed as community projects: <a target='_blank' href="https://projects.spring.io/spring-social/">https://projects.spring.io/spring-social/</a>. <br/><br/>
   I write a blog covering technical and opinion articles that can be found here: <a target='_blank' href="https://automateddeveloper.blogspot.com/">automateddeveloper.blogspot.com</a> (I am also a <a target='_blank' href="https://dzone.com/users/899489/rhinds.html">DZone MVB</a>)
